name: PrePreview

on:
  pull_request:

jobs:
  PrePreview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build site
        run: npm run site:preview

      - run: |
          zip -r _site.zip _site
      - name: upload _site artifact
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site.zip
          retention-days: 5

      - name: Save PR number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > ./pr-id.txt

      - name: Upload PR number
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ./pr-id.txt