name: MAIN_PULL_REQUEST

on:
  pull_request: 
    branches: [develop, master]

jobs:
  MAIN_PULL_REQUEST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/install-dep@develop
      - run: npm run lint
      - run: npm run test
