name: All_ON_PUSH

on: push
  # push:
  #   paths:
  #     - 'test/unit/*/*.test.js'
jobs:
  All_ON_PUSH:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/install-dep@develop
      - run: echo '${{ github.ref }} ...  ${{ github.sha }}''
      - name: 更新单元覆盖度徽章
        run: npm run test:coverage
        if: ${{ always() }}
      - run: npm run update:coverage-badge
      - name: build-site
        run: npm run site:preview
      - name: upload surge service
        id: deploy
        run: |
          export DEPLOY_DOMAIN=https://preview-${{ github.ref }}-tdesign-vue.surge.sh
          npx surge --project _site --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
      - run: echo 'https://preview-${{ github.ref }}-tdesign-vue.surge.sh'
        if: ${{ success() }}
      - run: echo "🍏 This job's status is ${{ job.status }}."