name: TAG_PUSH

on: create

jobs:
  Publish:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm i npm@latest -g
          npm install
        shell: bash
      - run: echo '${{ github.ref }} ...  ${{ github.ref_name }}'
      - name: Build site
        run: npm run site:preview
      - name: upload surge service
        id: deploy
        run: |
          export DEPLOY_DOMAIN=https://preview-${{ github.ref_name }}-tdesign-vue.surge.sh
          npx surge --project _site --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
      - run: echo 'https://preview-${{ github.ref_name }}-tdesign-vue.surge.sh'
        if: ${{ success() }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: npm run build
      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"